name: Triage issue
on:
  issues:
    types: [labeled, opened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  issues: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Nissuer
        uses: balazsorban44/nissuer@1.8.1
        with:
          label-area-prefix: ""
          label-area-section: "[Provider|Adapter] type(.*)### Environment"
          label-comments: '{ "incomplete": ".github/invalid-reproduction.md" }'
          reproduction-link-section: "### Reproduction URL(.*)### Describe the issue"
          reproduction-invalid-label: "invalid reproduction"
          reproduction-issue-labels: "bug"
          reproduction-blocklist: "github.com/nextauthjs.*"
